format: '&8(Discord) &7%name%: &f%message%'


#PLEASE DO NOT CHANGE ANYTHING BELOW. DOING SO COULD BREAK YOUR SYSTEM OR CORRUPT YOUR SERVER!

#---------------------------------#
#|           WARNING!            |#
#|   CHANGING THIS MAY CAUSE     |#
#|     UNEXPECTED BEHAVIOR!      |#
#---------------------------------#
token: ""