name: Hermes
version: "0.1 PRE-RELEASE"
main: io.github.aphelia.hermes.spigot.SpigotPlugin
description: "For connections to Aphelia"
load: STARTUP
commands:
  token:
    usage: /token
    description: Get the token to be printed to console.
    permission: comlink.token
    permission-message: "§cInsufficient Permissions!"